language: node_js
node_js:
  - 11.6.0
cache: yarn

notifications:
  email: false

before_install:
  - cd SmartHomeMobile

install:
  - yarn install

script:
  - yarn test

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
